"""
SmartRoute Agent Core 模块

导出核心基础组件
"""

from smartroute.core.config import Settings, get_settings, settings
from smartroute.core.exceptions import (
    AgentError,
    AllProvidersFailedError,
    AmbiguityDetectedError,
    CacheError,
    DatabaseError,
    ExternalAPIError,
    FallbackTriggeredError,
    IntentExtractionError,
    LLMContentFilterError,
    LLMError,
    LLMRateLimitError,
    LLMTimeoutError,
    MapAPIError,
    NoCandidatesError,
    NoFeasibleRouteError,
    POIDataError,
    PresentationError,
    ProfileNotFoundError,
    RetrievalError,
    RoutePlanningError,
    SchemaValidationError,
    SmartRouteError,
    SolverTimeoutError,
    StorageError,
    UGCAnalysisError,
    ValidationError,
    VectorStoreError,
)
from smartroute.core.logging import AgentLogger, get_logger, setup_logging
from smartroute.core.utils import (
    Timer,
    compute_category_similarity,
    compute_hash,
    format_cost_yuan,
    format_distance_km,
    format_duration_minutes,
    generate_plan_id,
    generate_session_id,
    generate_trace_id,
    is_business_hours_covered,
    merge_dicts,
    minutes_to_time,
    parse_relative_date,
    time_to_minutes,
    truncate_text,
)

__all__ = [
    # Config
    "Settings",
    "get_settings",
    "settings",
    # Exceptions
    "SmartRouteError",
    "LLMError",
    "LLMTimeoutError",
    "LLMRateLimitError",
    "LLMContentFilterError",
    "AllProvidersFailedError",
    "AgentError",
    "IntentExtractionError",
    "AmbiguityDetectedError",
    "ProfileNotFoundError",
    "RetrievalError",
    "NoCandidatesError",
    "UGCAnalysisError",
    "RoutePlanningError",
    "NoFeasibleRouteError",
    "SolverTimeoutError",
    "PresentationError",
    "StorageError",
    "DatabaseError",
    "CacheError",
    "VectorStoreError",
    "ExternalAPIError",
    "MapAPIError",
    "POIDataError",
    "ValidationError",
    "SchemaValidationError",
    "FallbackTriggeredError",
    # Logging
    "setup_logging",
    "get_logger",
    "AgentLogger",
    # Utils
    "generate_trace_id",
    "generate_session_id",
    "generate_plan_id",
    "time_to_minutes",
    "minutes_to_time",
    "parse_relative_date",
    "compute_hash",
    "merge_dicts",
    "truncate_text",
    "format_cost_yuan",
    "format_duration_minutes",
    "format_distance_km",
    "Timer",
    "compute_category_similarity",
    "is_business_hours_covered",
]